# Generated by Django 4.0.5 on 2022-06-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('product_type', models.CharField(max_length=15)),
            ],
        ),
    ]
