# Generated by Django 4.0.5 on 2022-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
